# version: "3"
# services:
#   db:
#     image: mysql:8
#     container_name: lifescience
#     restart: always
#     volumes:
#       - data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_DATABASE: ${DB_NAME}
#       MYSQL_USER: ${DB_USER}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#     ports:
#       - "3306:3306"
#     healthcheck:
#       test:
#         [
#           "CMD",
#           "mysql",
#           "-h",
#           "localhost",
#           "-u",
#           "root",
#           "-p${DB_PASSWORD}",
#           "-e",
#           "SELECT 1",
#         ]
#       timeout: 20s
#       retries: 10

#   lifesciences:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: lifescience
#     command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#     restart: always
#     volumes:
#       - .:/lifesciences
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       db: 
#         condition: service_healthy
# volumes:
#   data:






version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: employees
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: employees
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
      DB_PORT: 3306

volumes:
  mysql_data:
